Parameters:
  BucketName: 
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Name: !Ref BucketName
Outputs: 
  BucketArn: 
    Value: !GetAtt S3Bucket.Arn
  Id:
    Value: !Ref S3Bucket